### ISSUE TITLE
Visualizer does not show up in Rhythmbox

### ISSUE THREAD

**Issue by N0CashVa1ue** [fossfreedom/rhythmbox-spectrum#8]
After running install.sh and enabling the plugin in Rhythmbox when I go into "View" and click "Spectrum" it puts a checkmark next to "Spectrum" but nothing seems to happen. When running Rythmbox in the terminal and checking the box for Spectrum in "View" it outputs:

```
 Traceback (most recent call last):
  File "/home/nocashvalue/.local/share/rhythmbox/plugins/spectrum/spectrum_rb3compat.py", line 782, in _activate
    self._connect_func(action, None, self._connect_args)
  File "/home/nocashvalue/.local/share/rhythmbox/plugins/spectrum/spectrum.py", line 171, in toggle_visibility
    self._make_visible(action.get_active())
  File "/home/nocashvalue/.local/share/rhythmbox/plugins/spectrum/spectrum.py", line 176, in _make_visible
    self.spectrum.initialise(self.shell)
  File "/home/nocashvalue/.local/share/rhythmbox/plugins/spectrum/spectrum.py", line 257, in initialise
    self.spectrum = Gst.ElementFactory.make("spectrum", "spectrum")
  File "/usr/lib/python3.5/site-packages/gi/overrides/Gst.py", line 217, in make
    return Gst.ElementFactory.make(factory_name, instance_name)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Gst.py", line 348, in fake_method
    raise NotInitialized("Please call Gst.init(argv) before using GStreamer")
gi.overrides.Gst.NotInitialized: Please call Gst.init(argv) before using GStreamer
```
Afterword when I uncheck and then check the box again It also outputs
```
Traceback (most recent call last):
  File "/home/nocashvalue/.local/share/rhythmbox/plugins/spectrum/spectrum.py", line 403, in on_configure_event
    self.spectrum.set_property("bands", int(self.spect_bands))
AttributeError: 'SpectrumPlayer' object has no attribute 'spectrum'

(rhythmbox:6348): Gtk-WARNING **: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node viewport, owner GtkViewport)
Traceback (most recent call last):
  File "/home/nocashvalue/.local/share/rhythmbox/plugins/spectrum/spectrum.py", line 403, in on_configure_event
    self.spectrum.set_property("bands", int(self.spect_bands))
AttributeError: 'SpectrumPlayer' object has no attribute 'spectrum'
```
After that unchecking and checking the box does not output anything to the console unless I actually unload and reload the plugin or restart Rythmbox and then it just outputs the same stuff again and still the visualizer does not show up.

**Comment by fossfreedom** [comment]
Looks like you are missing a gstreamer component. What operating system and rhythmbox version are you running?

**Comment by N0CashVa1ue** [comment]
Kernel: x86_64 Linux 4.6.3-1-ARCH DE:Gnome 3.20.2 Rythymbox 3.3.1

**Comment by fossfreedom** [comment]
ok - the above commit will at least get the spectrum to display in its left-hand side orientation.

The sizing of the pane is screwed - it should be just the size of the spectrum max height bar.  No idea at the moment why GTK 3.18 and later has screwed up in this area.  Worked fine in previous GTK versions.
